root: true
plugins:
  - unused-imports
extends:
  - react-app
  - react-app/jest
  - plugin:prettier/recommended
ignorePatterns:
  - craco.config.js
rules:
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  'react-hooks/exhaustive-deps': 'off'
  unused-imports/no-unused-imports: 1
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - sibling
      pathGroups:
        - pattern: 'src/**'
          group: internal
          position: before
      pathGroupsExcludedImportTypes:
        - builtin
      alphabetize:
        order: asc
        caseInsensitive: false
      newlines-between: always-and-inside-groups
      warnOnUnassignedImports: true
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/*.test.{ts,js}'
        - '**/*.spec.{ts,js}'
        - 'scripts/**/*.{ts,js}'
        - 'test/**/*.{ts,js}'
overrides:
  - files:
      - 'mocks/**/*.{ts,js}'
    rules:
      import/no-extraneous-dependencies: 'off'
  - files:
      - '**/*.@(story|stories).*'
    rules:
      import/no-anonymous-default-export: 'off'
  - files:
      - setupTests.ts
      - '**/*.test.tsx'
      - '**/*.test.ts'
      - '**/*.@(story|stories).*'
    rules:
      import/no-extraneous-dependencies: 'off'
